databases:
  - name: values-in-the-wild-db
    plan: free

services:
  - type: web
    name: values-in-the-wild
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://valuesinthewild.com,https://www.valuesinthewild.com,https://values-in-the-wild.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: values-in-the-wild-db
          property: connectionString
